### ISSUE TITLE
Error in Xcode 6.3

### ISSUE THREAD

**Issue by orangecoding** [varshylmobile/MapManager#3]
Hi,

in Xcode 6.3/Swift 1.2 I'll get an error "Ambiguous use of operator -" twice. Are you planning to fix this anytime soon?

**Comment by varshylmobile** [comment]
Hello Christian,
I am a bit busy these days..i will try to look into this bug over the weekend. In case you find a fix, please send a PR.

**Comment by varshylmobile** [comment]
Updated for XCode 6.4 Beta and iOS 8.4 beta
Download the latest version

**Comment by orangecoding** [comment]
Nice. Thanks.
