### ISSUE TITLE
Overlay not visible on the map

### ISSUE THREAD

**Issue by alikazim** [varshylmobile/MapManager#5]
I cant see the overlay route on my map. 
Its only move and focus my map to origin and Destination in bounding rect but I cant see the Rout Overlay. please help

I have done like this

            var mapManager = MapManager()
            
            var coordinateStart = CLLocationCoordinate2D(latitude: (start_lat as NSString).doubleValue, longitude: (start_lng as NSString).doubleValue)
            
             var coordinateEnd = CLLocationCoordinate2D(latitude: (end_lat as NSString).doubleValue, longitude: (end_lng as NSString).doubleValue)
            
            mapManager.directions(from: coordinateStart, to: coordinateEnd) { (route, directionInformation, boundingRegion, error) -> () in
                
                if (error != nil) {
                    
                    println(error!)
                    
                }else{
                    
                    if let web = self.mapView{
                        
                        dispatch_async(dispatch_get_main_queue()) {
                            
                            web.addOverlay(route!)
                            web.setVisibleMapRect(boundingRegion!, animated: true)
                            
                        }
                        
                    }
                }
                
            }

**Comment by vincentleeuwen** [comment]
Had this initially as well. You need to update your `mapView` as follows: (assuming you've sorted out MKMapViewDelegate)

```swift
func mapView(mapView: MKMapView!, rendererForOverlay overlay: MKOverlay!) -> MKOverlayRenderer! {
        
        if overlay.isKindOfClass(MKPolyline) {
            // draw the track
            let polyLine = overlay
            let polyLineRenderer = MKPolylineRenderer(overlay: polyLine)
            polyLineRenderer.strokeColor = UIColor.orangeColor()
            polyLineRenderer.lineWidth = 3.5
            return polyLineRenderer
        }
        return nil
    }
```

**Comment by alikazim** [comment]
Thanks that Helped me.

Now how to remove this and/or all overlays. I have tried like this

               var overlays = mapView.overlays
               mapView.removeOverlays(overlays)

But nothing happens, Overlay remains on the map
